[package]
name = "adv2020_8"
version = "0.1.0"
authors = ["Andrew Smith <andy@robotlovesyou.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.4.2"
indoc = "1.0"
